[book]
authors = ["zafu-acm-team"]
language = "zh-cn"
multilingual = false
src = "src"
title = "ZAFU ACM Wiki"


[output.html]
additional-css = ["_static/custom.css"]
git-repository-url = "https://github.com/zafuacm/wiki/"
edit-url-template = "https://github.com/zafuacm/wiki/edit/main/{path}"

[output.html.fold]
enable = true
level = 1

[preprocessor.katex]
